# Generated by Django 5.2.3 on 2025-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteslike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesLike',
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
