# Generated by Django 5.2.3 on 2025-06-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
