# Generated by Django 5.2.3 on 2025-06-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
